### ISSUE TITLE
Round 4 Pre-Launch Bug Fixes

### ISSUE THREAD

**Issue by jadesym** [siddharthgutta/Entree.LegacyServer#316]
## Necessary/SUPER High Priority
- [x] **Show Order Total in cart** #318 @jlmao 
- Show order total in the cart so people know how much they're paying
- [x] **Send receipt back to the customer** #319 @jlmao
- Send text receipt with the contents of the order, prices, and such when order is ACCEPTED
- Christoph asked if the customers asked for a receipt how would they get this
- Solution: send the receipt back in text form
- [x] **ORDER NUMBER sent when order accepted** #342 @jlmao
- Order number should be sent to the customer when order is accepted
- Instructions on telling the producer employee your order/name would be cool too
- [x] **Type is clearer than Pick/Select** #325 @jlmao
- Joel thought pick/select could be slightly confusing
- [x] **Call to Action at bottom of text** #326 
- Action should be last sentence of text
- [x] **Credit Card Payment Incorrect** #327 @jadesym
- Even though order went through, the response message said incorrect credit card
- Sent back to same page with credit card info gone, should instead jump to your payment has been processed or some form of success page
- [ ] **Correct CC Payment** #351
- Correct CC Payment should go to success page with a message that says 'Your account information and credit card has been updated' instead of the same CC submission page
- Can remove the alert and replace with success page
- [x] **Lock Icons on Profile Page** #328 
- Also something like secure by Braintree Payments or something
- Even Paypal too since Paypal owns Braintree
- http://paidmembershipspro.com/wp-content/themes/2013-pmpro/images/Braintree.gif
- https://eventespresso.com/wp-content/uploads/2015/11/35222_paymentbraintree.png
- [x] **/menu fails after order completed** #332 @jlmao
- https://files.slack.com/files-pri/T0GU54CCX-F0Z107GA0/screenshot_20160407-224437.png
- https://files.slack.com/files-pri/T0GU54CCX-F0Z139ULW/screenshot_20160407-224442.png
- https://files.slack.com/files-pri/T0GU54CCX-F0Z13A72A/screenshot_20160407-223024.png
- [x] **Forces them to checkout** #333  @jlmao
- https://paper.imgix.net/https%3A%2F%2Fd2mxuefqeaa7sj.cloudfront.net%2Fs_F942D601ED2B3DE208456A55D218720CBA9E87F395CBA9E4D1657784DDE90EE6_1460074072768_IMG_2282.PNG?ixlib=js-0.2.1&s=6bc58f856fada4254d426c9f6c4285dd
- [x] **Clear chatState when order accepted or declined** #335 @jlmao
- should be able to do other things by emptying order in chatstate
- [x] **Mac Daddy's Showing closing at 11PM** #336 @jadesym
- should be 10PM closing
- https://files.slack.com/files-pri/T0GU54CCX-F0Z1N4H34/slack_for_ios_upload.png
- [ ] **Sign In/Sign Out Enable/Disable** #337 
- Sign out should auto disable
- Sign In should auto enable if within the hours
- [ ] **Auto Disable/Enable on Hours** #338 
- disable when hours reach closing time
- enable when hours reach opening time, given app is open
- [ ] **Change Credit Card Statment Text** #339  @jadesym
- Currently shows: BT _ENTREE_MAC DJZT73R FORT WORTH TX
- [x] **COMPLETED order text message** #343 @jlmao
- completed orders should be more clear to the customer
- customer should know that the order has been finished cooking and is ready for cooking
- 'Your order is ready' is too vague and too similar to the other messages, should give more explicit instructions
## High Priority
- [x] **Different notification sound** #317  TEST WHAT SOUNDS WE LIKE
- Christoph said the sound was too similar to his texts, and he ignores those
- Need a unique sound
- [x] **Login Screen Issue** #320 
- Login screen still is squished on Christoph's phone Samsung Galaxy
- [ ] **Order Summary/Invoice** VERY IMPORTANT #321 
- Christoph wants to know all the orders that came in/how much money
- Wants to see all individual orders to make sure all money/orders are accounted for
- Christoph wants this in e-mail form
- [x] **HISTORY Button** #322 
-  Move all Picked up and Declined Orders here
- Change text from Decline to History
- Should show history of orders that are completed as well as declined orders
- Christoph can use this to compare with his invoice/order summary
- [x] **Change DECLINED arrow buttton** #323 
- Typo: should say Completed instead
- [x] **ORDER Visibility** #324 
- at the top of the individual order screen should show order # and name more clearly
- Christoph didn't know to check details button
- [x] **Void/Refund Payments** @jadesym #329 
- implement voiding payments
- use on decline to refund money back
- [x] **Release From Escrow** @jadesym #330 
- release money to Christop's bank account functionality
- [ ] **Decline Message** #331 
- Decline message works, but isn't that clear
- The text that is sent back to the user should say that that specific text response is from the restaurant itself
- [ ] **Rename id2** #334 
- id2 just needs to be some more clear in naming, maybe order# or something
- [x] **Void Non-Real Payments** #340  @jadesym
- Void all non $20.75
- Void all non-Joel
- Clear these from database, so they don't show up on history
## MEDIUM PRIORITY
- [ ] **Implement Convenience Fee** @jadesym
- Consumer Side Convenience Fee
- [ ] **Auto Disable/Enable on Toggle** STILL NEEDS TO BE DISCUSSED
- Still needs to be discussed further
- Possibly sending closing/opening times to the app whenever you toggle
- [ ] **APP iOS Freeze**
- [ ] **App Forced Updates**
  - When app is out of date, force user to update the producer app
- [ ] **Mysterious Black Box**  TRY TO REPRODUCE
- Sometimes a random black box
- appears on the app, but goes away after rotating the screen
- [ ] **Quantities Shown in Cart**
- Show quantities rather than duplicates
- Make Box with number quantity show 1x instead of 1 to show how many
- [ ] **Restaurant Descriptions**
- From: Here are items from macdaddys0) The Meltdown - $3.5 1) The Spicy Pig - $3.5 2) The Funky Chunky - $3.5 3) The Vatican - $3.5 4) The Garden - $4 Type a number to select an item, or type "menu" to see the entire menu
- To: MacDaddy’s is a food truck that serves gourmet mac and cheese creation. Here are my recommended items:
  The Meltdown:
  The Spicy Pig
  The Funky Chunky
  The Vatican
  The Garden Pick a number for an item you want or type /menu to see the full menu
## LOW PRIORITY
- [ ]  **MESSENGER: Messages not being shown in the correct order**
- Ex: “/r” message showing up after the message showing the list of available restaurants
- [ ] **MESSENGER: Optimize messages**
- [ ] **MESSENGER: Make text on Messenger Selectable for Copy/Paste**
